apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: bookstore
  labels:
    app: user
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 50054
    targetPort: 50054
    protocol: TCP
    name: grpc
  selector:
    app: user


