apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: bookstore
  labels:
    app: payment
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 50056
    targetPort: 50056
    protocol: TCP
    name: grpc
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: health
  selector:
    app: payment


