apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: bookstore
  labels:
    app: catalog
    service: catalog
data:
  SERVICE_NAME: "catalog"
  GRPC_PORT: "50051"
  HTTP_HEALTH_PORT: "8080"
  LOG_LEVEL: "info"
  INVENTORY_SERVICE_URL: "inventory:50055"





