apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: bookstore
  labels:
    app: order
    component: backend
data:
  SERVICE_NAME: "order"
  GRPC_PORT: "50053"
  HTTP_HEALTH_PORT: "8082"
  LOG_LEVEL: "INFO"
  DATABASE_URL: "postgresql+psycopg2://bookstore:bookstore@postgres:5432/bookstoredb"
  CATALOG_SERVICE_URL: "catalog:50051"
  CART_SERVICE_URL: "cart:50052"


