apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: bookstore
  labels:
    app: inventory
    component: backend
data:
  SERVICE_NAME: "inventory"
  GRPC_PORT: "50055"
  HTTP_HEALTH_PORT: "8083"
  LOG_LEVEL: "info"
  PG_DSN: "postgres://bookstore:bookstore@postgres:5432/bookstoredb?sslmode=disable"
  RABBITMQ_URL: "amqp://admin:changeme@rabbitmq:5672/"


