apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: bookstore
  labels:
    app: inventory
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 50055
    targetPort: 50055
    protocol: TCP
    name: grpc
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: health
  selector:
    app: inventory


